// @ts-ignore - This file is generated by the build step before Vercel deploy output.
import server from "../dist/server/index.js";

export const config = {
  runtime: "nodejs",
};

function getOrigin(req: any): string {
  const forwardedProto = req.headers?.["x-forwarded-proto"];
  const protocol = Array.isArray(forwardedProto)
    ? forwardedProto[0]
    : forwardedProto || "https";
  const host = req.headers?.host || "localhost";
  return `${protocol}://${host}`;
}

export default async function handler(req: any, res: any) {
  const requestUrl = new URL(req.url || "/", getOrigin(req));

  const requestInit: RequestInit = {
    method: req.method,
    headers: req.headers,
  };

  if (req.method !== "GET" && req.method !== "HEAD") {
    requestInit.body = req;
    // Required by Node when passing a stream body to fetch Request.
    (requestInit as RequestInit & { duplex: "half" }).duplex = "half";
  }

  const request = new Request(requestUrl, requestInit);
  const response = await server.fetch(request, {}, {});

  res.statusCode = response.status;
  response.headers.forEach((value: string, key: string) => {
    res.setHeader(key, value);
  });

  if (!response.body) {
    res.end();
    return;
  }

  const body = Buffer.from(await response.arrayBuffer());
  res.end(body);
}